models/contacts.py
from utils.db import db

class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    full_name = db.Column(db.String(100))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100))

    def __init__(self, full_name, email, phone):
        self.full_name = full_name
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy

from config import DATABASE_CONNECTION_URI

app = Flask(__name__)

app.secret_key = "secret_key"
app.config['SQLALCHEMY_DATABASE_URI'] = DATABASE_CONNECTION_URI
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

SQLAlchemy(app)

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contacts import Contact
from utils.db import db

contacts = Blueprint('contacts', __name__,)

@contacts.route('/')
def index():
    contacts = Contact.query.all()
    return render_template('index.html', contacts=contacts)

@contacts.route('/new-contact', methods=['POST'])
def add_contact():
    full_name = request.form['fullname']
    email = request.form['email']
    phone = request.form['phone']

    new_contact = Contact(full_name, email, phone)

    db.session.add(new_contact)
    db.session.commit()

    flash("Contact added successfully!")
    return redirect(url_for('contacts.index'))

@contacts.route('/update-contact/<id>', methods=['GET', 'POST'])
def update_contact(id):
    contact = Contact.query.get(id)

    if request.method == 'POST':
        contact = Contact.query.get(id)
        contact.full_name = request.form['fullname']
        contact.email = request.form['email']
        contact.phone = request.form['phone']

        db.session.commit()
        flash("Contact updated successfully!")
        return redirect(url_for('contacts.index'))

    return render_template('update_contact.html', contact=contact)

@contacts.route('/delete-contact/<id>')
def delete_contact(id):
    contact = Contact.query.get(id)

    db.session.delete(contact)
    db.session.commit()

    flash("Contact deleted successfully!")
    return redirect(url_for('contacts.index'))

@contacts.route('/about')
def about():
    return render_template('about.html')

templates/about.html
{% extends 'layout.html' %}

{% block content %}

<div>
    <h1 class="text-light">About</h1>
    <p class="text-light">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis cupiditate blanditiis earum laudantium, nostrum
        quisquam tempore architecto consectetur distinctio omnis quibusdam maiores perspiciatis minus obcaecati provident
        non minima fugit dolorum eum eligendi doloribus rerum? Fugiat at, id nulla harum commodi velit quidem distinctio a
        consequuntur quis corrupti quam nesciunt, officia suscipit explicabo repudiandae ea quae, aut quia esse minus nisi
        iste excepturi! Nulla ratione quod cumque laborum eveniet perferendis sapiente, id corrupti ab voluptates, hic velit
        vel quis? Inventore sint in aperiam quaerat qui! Libero aspernatur aut impedit nostrum, reiciendis consequatur,
        ipsum molestiae quaerat adipisci, cum voluptate illo. Perspiciatis debitis ducimus excepturi, impedit quasi qui
        neque praesentium necessitatibus dignissimos reiciendis, inventore in laborum explicabo maiores suscipit veritatis
        ab magni enim blanditiis perferendis nostrum! Enim asperiores, molestias illo maxime repellat facilis necessitatibus
        esse amet autem omnis saepe eius minus? Fugit debitis explicabo optio quod enim officia velit suscipit, quibusdam
        laudantium quo quam ducimus fugiat asperiores harum? Facere ducimus corrupti sequi tempora quos suscipit numquam,
        doloremque deserunt saepe rem deleniti unde quod. Explicabo, totam voluptatibus veniam sit molestias exercitationem
        repellat? Perspiciatis asperiores quas inventore fugiat architecto dolorem, placeat vel ratione quae odio
        aspernatur. Quo consequuntur qui itaque repellendus. Autem doloribus aspernatur amet non. Tempora dignissimos minus
        iure modi? Dolorem commodi obcaecati nam consectetur aperiam voluptate provident sed, optio ipsa dolorum
        praesentium. Eum, quasi iure! A fuga quasi recusandae autem omnis error maiores, consequuntur officia quidem soluta
        eos aliquid vero suscipit quae, laboriosam veritatis veniam temporibus asperiores cumque architecto obcaecati. Nulla
        dolores id ipsum ab exercitationem accusamus reiciendis labore delectus. Eos, cumque cum voluptas, ea, nostrum et
        dignissimos quod blanditiis pariatur ratione aliquam fugit magni rerum tempora nam labore consequatur ad? Accusamus,
        dignissimos! Eaque quam consequuntur ea labore illo voluptatibus quibusdam ipsa! Inventore iusto placeat reiciendis
        laboriosam nulla explicabo blanditiis eaque, asperiores nostrum?</p>
</div>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block content %}

<div class="row">
    <div class="col-md-5">
        {% include('partials/_messages.html') %}
        {% include('partials/_contact_form.html') %}
    </div>
    <div class="col-md-7">
        {% for contact in contacts %}

        <div class="card mb-1 text-white bg-dark">
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h5>{{ contact.full_name }}</h5>
                    <div>
                        <a class="btn bg-black btn-sm rounded-0 text-white" href="{{ url_for('contacts.update_contact', id=contact.id) }}">Update</a>
                        <a class="btn btn-danger btn-sm rounded-0" href="{{ url_for('contacts.delete_contact', id=contact.id) }}">Delete</a>
                    </div>
                </div>
                <p>{{ contact.email }}</p>
                <p>{{ contact.phone }}</p>
            </div>
        </div>

        {% endfor %}
    </div>
</div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flask SQLAlchemy CRUD</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
</head>
<body>
    {% include('partials/_navbar.html') %}

    <div class="container p-2">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

templates/partials/_contact_form.html
<form action="/new-contact" method='POST' class='card  bg-dark text-light'>
    <div class="card-body p-4">
            <div class="mb-3">
                <label for="fullname">Write your fullname:</label>
                <input type="text" name="fullname" placeholder="Write your fullname"
                    class='form-control rounded-8 bg-dark border-0 text-light'>
            </div>
            <div class="mb-3">
                <label for="email">Write your email:</label>
                <input type="text" name="email" placeholder="Write your email" class='form-control rounded-8 bg-dark border-0 text-light'>
            </div>
            <div class="mb-3">
                <label for="phone">Write your phone:</label>
                <input type="text" name="phone" placeholder="Write your phone" class='form-control rounded-8 bg-dark border-0 text-light'>
            </div>
            <button class="btn btn-primary">Save</button>
    </div>
</form>

templates/partials/_messages.html
{% with messages = get_flashed_messages() %}

    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{message}}
        </div>
        {% endfor %}
    {% endif %}

{% endwith %}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">Flask SQLAlchemy CRUD</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/about">About</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/update_contact.html
{% extends 'layout.html' %}

{% block content %}

<div class="col-md-7 offset-md-2">
    <form action="/update-contact/{{contact.id}}" method='POST' class='card bg-dark text-light'>
        <div class="card-body p-4">
            <div class="mb-3">
                <label for="fullname">Update your fullname:</label>
                <input type="text" name="fullname" placeholder="Wirte your fullname" value="{{contact.full_name}}"
                    class='form-control rounded-8 bg-dark border-0 text-light'>
            </div>
            <div class="mb-3">
                <label for="email">Update your email:</label>
                <input type="text" name="email" placeholder="Wirte your email" value="{{contact.email}}"
                    class='form-control rounded-8 bg-dark border-0 text-light'>
            </div>
            <div class="mb-3">
                <label for="phone">Update your phone:</label>
                <input type="text" name="phone" placeholder="Wirte your phone" value="{{contact.phone}}"
                    class='form-control rounded-8 bg-dark border-0 text-light'>
            </div>
            <button class="btn btn-secondary">Update</button>
        </div>
    </form>
</div>

{% endblock %}